### ISSUE TITLE
sabte kharid tekrari dar panel

### ISSUE THREAD

**Issue by samii00** [hojjat-reyhane/Cafebazaar-IAB-for-Unity#1]
سلام و تشکر از پکیج خوبتون
من مشکلی مشاهده کردم که نیازمند کمک شماست
در پنل کافه بازار بارها مشاهده کردم که یک کاربر در عرض یک دقیقه دو سه بار یک محصول یکسان رو خریده (محصول مصرفی) و  چنین حالتی غیر معمول هست!!
همچنین کافه بازار در مستنداتش عنوان کرده که تا یک محصول مصرف نشود قابلیت خرید دوباره آن وجود ندارد
ایراد از چی میتونه باشه؟؟

**Comment by hojjat-reyhane** [comment]
سلام
اگر محصول مصرفی باشه به هیچ عنوان مشکلی وجود نداره
تعدادی از کاربرها ممکنه پشت سر هم یک بسته رو خریداری کنن و به هیچ عنوان غیر معمول نیست
مثلا بسته ۵۰۰ تا سکه رو سه بار بخره تا ۱۵۰۰ سکه داشته باشه
این میتونه ناشی از این باشه که تنوع محصولات شما کمه و کاربر با چند بار خریدن بسته‌ها نیازش رو برطرف میکنه

**Comment by samii00** [comment]
ممنون از پاسختون
من طبق پروژه نمونه
 TrivialDrive
سکه کاربر رو در متد 
consumePurchaseSucceededEvent
 بهش میدم حالا اگر خریدش انجام بشه ولی این متد موفقیت آمیز نباشه چی؟
و کاربر فک کنه پول از حسابش کم نشده و دوباره روی همون بسته **یا بسته دیگری** بزند ؛
در این حالت آیا چک میشه که هر خرید مصرف نشده ای وجود داره مصرف شود و **خرید جدیدی شروع نشود** یا مثلا ما خودمون باید این چک رو انجام بدیم؟

**Comment by hojjat-reyhane** [comment]
در این حالت خرید کاربر در بازار ثبت شده، اما چون مصرف نشده، محصول بهش داده نمیشه
اگر کاربر مجدد اقدام به خرید اون محصول کنه، بازار تشخیص میده که این محصول خریداری شده اما مصرف نشده، و از کاربر هزینه‌ای دریافت نمیکنه. در این حالت نتیجه خرید موفقیت آمیز برگشت داده میشه و پلاگین مجدد اقدام به مصرف محصول میکنه
طی این فرآیند خرید جدیدی توی پنل شما ثبت نمیشه
خطا در مصرف کردن محصول عملا اتفاق نمیافته، مگر حالتی که قبلش بخواین اعتبار خرید رو تایید کنید و اونجا خطا اتفاق بیافته

**Comment by samii00** [comment]
خیلی ممنووون
اگر اقدام به خرید یک بسته دیگر کند خرید اول همچنان مصرف نشده باقی میماند و سکه خرید اول را دریافت نمیکند درسته؟
و آیا ما باید همچین مسأله ای رو هنگام کلیک روی خرید بسته هامون چک کنیم؟

و آیا زمانی که به توصیه کافه بازار در ابتدای بازی ما متد
queryInventory
رو صدا میزنیم اگر محصول مصرف نشده ای وجود داشته باشه بصورت خودکار متد
consume 
فراخوانده میشه یا باید بصورت دستی باید تشخیص و مصرف شوند؟

**Comment by hojjat-reyhane** [comment]
خرید قبلی با خرید جدید تحت تاثیر قرار نمیگیره و نیازی به چک کردن ندارید
چک کردن اینونتوری فقط استعلام این هست که محصول مصرف شده یا خیر، در ادامه اگر نیاز باشه خودتون باید به صورت دستی مصرف کنید
پیشنهاد من اینه که زمان بذارید و ابعاد مختلف پرداخت رو خودتون تست کنید تا تسلط بهتری بهش پیدا کنید
