### ISSUE TITLE
The Raw `INAPP_PURCHASE_DATA` for the Purchase Signature is MISSING

### ISSUE THREAD

**Issue by CodeMasterYi** [hojjat-reyhane/Cafebazaar-IAB-for-Unity#5]
How Can I Find the Raw `INAPP_PURCHASE_DATA` for the purchase Signature?

**Comment by hojjat-reyhane** [comment]
I didn't get exactly what you meant!
What do you need it for?

**Comment by CodeMasterYi** [comment]
![BDA88C59-14A0-44B3-9973-52B9363720AB](https://user-images.githubusercontent.com/10430162/97266444-6fb69e00-1863-11eb-8fa2-43dd637f19b0.png)
The Origin Json is important for server-side verification. you lost the raw data.

**Comment by CodeMasterYi** [comment]
![1D4F3F30-DB56-4BDD-92F7-D2B84752F2D1](https://user-images.githubusercontent.com/10430162/97266720-ea7fb900-1863-11eb-9c45-eb1bbe8ef4af.png)
the raw `INAPP_PURCHASE_DATA` is needed in server-side signature verification.~

**Comment by CodeMasterYi** [comment]
Long for your help!

**Comment by hojjat-reyhane** [comment]
I was checking the problem.
The original Json is not included because of the problem due to putting one Json in another then passing it to Unity and parsing the data.
I think you can regenerate it on Unity side with the data in Purchase class.
Although you can just use the Purchase.OrderId and SKU for server-side verification using Bazaar API. It's completely reliable.

**Comment by CodeMasterYi** [comment]
`I think you can regenerate it on Unity side with the data in Purchase class.`
Fields' Order is Important for signature verification.

**Comment by hojjat-reyhane** [comment]
Yes you're right.
If I give you the Jar which prints the original Json can you fix it by yourself?
I really have limited time today for full testing.

**Comment by hojjat-reyhane** [comment]
I checked again. Currently the purchase result is printing which is actually the original Json + itemType + signature.
So the order is not changed, you just have to remove itemType and signature from the end of Purchase.json.
The order is: 
orderId, packageName, productId, purchaseTime, purchaseState, developerPayload, purchaseToken

**Comment by CodeMasterYi** [comment]
OK, thank you for your help.
